// this file was generated by gomacro command: import _i "/Users/williamnharvey/workspace/gomacro/_example/williamnharvey/williamnharveyfrontend"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package williamnharveyfrontend

import (
	r "reflect"
	context "context"
)


/**
 * Declare and fill a global variable Packages, whose type is compatible
 * with the global variable github.com/WilliamNHarvey/gomacro/imports.Packages
 *
 * If you want to automatically register this package's declarations into
 *   github.com/WilliamNHarvey/gomacro/imports.Packages
 * to let gomacro know about this package, and allow importing it without compiling
 * a plugin, you can add the following to some _other_ file in this directory:
 *
 * import "github.com/WilliamNHarvey/gomacro/imports"
 *
 * func init() {
 *     for k, v := range Packages {
 *         imports.Packages[k] = v
 *     }
 * }
 *
 * Such code is _not_ automatically added to this file, because it would introduce
 * a dependency on gomacro packages, which may be undesiderable.
 */

type Package = struct {
	Name     string
	Binds    map[string]r.Value
	Types    map[string]r.Type
	Proxies  map[string]r.Type
	Untypeds map[string]string
	Wrappers map[string][]string
}

var Packages = make(map[string]Package)

// reflection: allow interpreted code to import "github.com/WilliamNHarvey/gomacro/_example/williamnharvey/williamnharveyfrontend"
func init() {
	Packages["github.com/WilliamNHarvey/gomacro/_example/williamnharvey/williamnharveyfrontend"] = Package{
		Name: "williamnharveyfrontend",
		Binds: map[string]r.Value{
			"DoSomethingWithInterfaceStruct":	r.ValueOf(DoSomethingWithInterfaceStruct),
			"InteractableBackend":	r.ValueOf(&InteractableBackend).Elem(),
			"Packages":	r.ValueOf(&Packages).Elem(),
		}, Types: map[string]r.Type{
			"Backend":	r.TypeOf((*Backend)(nil)).Elem(),
			"InterfaceStruct":	r.TypeOf((*InterfaceStruct)(nil)).Elem(),
			"P__Users_williamnharvey_workspace_gomacro__example_williamnharvey_williamnharveyfrontend_Backend":	r.TypeOf((*P__Users_williamnharvey_workspace_gomacro__example_williamnharvey_williamnharveyfrontend_Backend)(nil)).Elem(),
			"Package":	r.TypeOf((*Package)(nil)).Elem(),
		}, Proxies: map[string]r.Type{
			"Backend":	r.TypeOf((*P__Users_williamnharvey_workspace_gomacro__example_williamnharvey_williamnharveyfrontend_Backend)(nil)).Elem(),
		}, 
	}
}

// --------------- proxy for github.com/WilliamNHarvey/gomacro/_example/williamnharvey/williamnharveyfrontend.Backend ---------------
type P__Users_williamnharvey_workspace_gomacro__example_williamnharvey_williamnharveyfrontend_Backend struct {
	Object	interface{}
	DoSomethingWithInterfaceStruct_	func(interface{}, context.Context, *InterfaceStruct) (*InterfaceStruct, error)
}
func (P *P__Users_williamnharvey_workspace_gomacro__example_williamnharvey_williamnharveyfrontend_Backend) DoSomethingWithInterfaceStruct(unnamed0 context.Context, unnamed1 *InterfaceStruct) (*InterfaceStruct, error) {
	return P.DoSomethingWithInterfaceStruct_(P.Object, unnamed0, unnamed1)
}
